### ISSUE TITLE
probe scraper moz central task now taking 12+ hours to run in airflow

### ISSUE THREAD

**Issue by relud** [mozilla/probe-scraper#633] opened 2023-10-10 16:23 UTC
https://workflow.telemetry.mozilla.org/dags/probe_scraper/grid

the probe scraper moz central task consistently took less than 3 hours to run, until 2023-09-30. starting on 2023-10-06 the task has been taking over 12 hours to run.

**Comment by akkomar** [comment] 2023-10-26 07:45
Moz central job is back to normal. This might have been caused by resource contention on the cluster, around the time this happened we had a problem with multiple pods being ran per task. This was addressed by enabling `reattach_on_restart` setting in the heaviest DAGs (copy_deduplicate and GLAM), last of these PRs was: https://github.com/mozilla/telemetry-airflow/pull/1837

**Closed** 2023-10-26 07:45 UTC
